version: '3.9'

services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5436:5432
  sqitch:
    image: sqitch/sqitch
    volumes:
      - ./schema:/repo
      - ./config:/home

volumes:
  fmc_db_data:
